package net.arg3.jmud;

// default package
// Generated 12-Sep-2009 1:43:25 AM by Hibernate Tools 3.2.5.Beta
import javax.persistence.Entity;

import net.arg3.jmud.interfaces.IDataObject;

/**
 * PcRace generated by hbm2java
 */
@Entity
public abstract class PcRace extends Race implements IDataObject<Integer> {

	private static final long serialVersionUID = 1L;
}
