package net.arg3.jmud;

// default package
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import net.arg3.jmud.interfaces.IDataObject;

/**
 * Shop generated by hbm2java
 */
@Entity
@Table(name = "shop")
public class Shop implements IDataObject<Integer> {

	private static final long serialVersionUID = 1L;
	private int id;
	private NonPlayer owner;
	private int profitBuy;
	private int profitSell;
	private int openHour;
	private int closeHour;

	@Override
	public int compareTo(IDataObject<Integer> o) {
		return getId().compareTo(o.getId());
	}

	@Column(name = "close_hour", nullable = false)
	public int getCloseHour() {
		return this.closeHour;
	}

	@Id
	@Column(name = "shop_id", nullable = false, columnDefinition = "int")
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Override
	public Integer getId() {
		return this.id;
	}

	@Column(name = "open_hour", nullable = false)
	public int getOpenHour() {
		return this.openHour;
	}

	@OneToOne(targetEntity = NonPlayer.class, fetch = FetchType.EAGER)
	@JoinColumn(name = "char_id", nullable = false)
	public NonPlayer getOwner() {
		return this.owner;
	}

	@Column(name = "profit_buy", nullable = false)
	public int getProfitBuy() {
		return this.profitBuy;
	}

	@Column(name = "profit_sell", nullable = false)
	public int getProfitSell() {
		return this.profitSell;
	}

	public void setCloseHour(int closeHour) {
		this.closeHour = closeHour;
	}

	@Override
	public void setId(Integer value) {
		id = value;
	}

	public void setOpenHour(int openHour) {
		this.openHour = openHour;
	}

	public void setOwner(NonPlayer owner) {
		this.owner = owner;
	}

	public void setProfitBuy(int profitBuy) {
		this.profitBuy = profitBuy;
	}

	public void setProfitSell(int profitSell) {
		this.profitSell = profitSell;
	}
}
