package net.arg3.jmud;

import javax.persistence.Column;

/**
 * Spell generated by hbm2java
 */
public abstract class Spell extends Ability {

	private static final long serialVersionUID = 1L;
	private int manaCost;

	@Column(name = "mana_cost")
	public int getManaCost() {
		return this.manaCost;
	}

	public void setManaCost(int manaCost) {
		this.manaCost = manaCost;
	}

	public static Spell lookup(long id) {
		for (Ability a : getList()) {
			if (a instanceof Spell && a.getId() == id) {
				return (Spell) a;
			}
		}
		return null;
	}

	public static Spell lookup(String name) {
		for (Ability a : getList()) {
			if (a instanceof Spell && Jmud.isName(a.getName(), name)) {
				return (Spell) a;
			}
		}

		return null;
	}
}
